import prettier from 'eslint-config-prettier';
import path from 'node:path';
import { includeIgnoreFile } from '@eslint/compat';
import js from '@eslint/js';
import playwright from 'eslint-plugin-playwright';
import svelte from 'eslint-plugin-svelte';
import { defineConfig } from 'eslint/config';
import globals from 'globals';
import ts from 'typescript-eslint';
import svelteConfig from './svelte.config.js';

const gitignorePath = path.resolve(import.meta.dirname, '.gitignore');

export default defineConfig(
	includeIgnoreFile(gitignorePath),
	{
		ignores: [
			'src/lib/types/storyblok.d.ts',
			// Generated Cloudflare bindings type file — contains eslint-disable directives
			// that aren't needed and can't be removed (file is regenerated by wrangler)
			'src/worker-configuration.d.ts'
		]
	},
	js.configs.recommended,
	ts.configs.recommendedTypeChecked,
	svelte.configs.recommended,
	prettier,
	svelte.configs.prettier,
	{
		languageOptions: {
			globals: { ...globals.browser, ...globals.node },
			parserOptions: {
				projectService: {
					// These root-level files are not included in the SvelteKit-generated tsconfig;
					// allow them with a default project. vite.config.ts and playwright.config.ts
					allowDefaultProject: [
						'eslint.config.js',
						'commitlint.config.js',
						'storyblok.config.ts',
						'svelte.config.js',
						'scripts/*.mjs'
					]
				},
				tsconfigRootDir: import.meta.dirname
			}
		},
		rules: {
			// typescript-eslint strongly recommend that you do not use the no-undef lint rule on TypeScript projects.
			// see: https://typescript-eslint.io/troubleshooting/faqs/eslint/#i-get-errors-from-the-no-undef-rule-about-global-variables-not-being-defined-even-though-there-are-no-typescript-errors
			'no-undef': 'off',
			'no-console': ['error', { allow: ['warn', 'error'] }],
			// Prefer type annotations (`const x: T = ...`) over type assertions (`... as T`).
			'@typescript-eslint/consistent-type-assertions': [
				'error',
				{
					assertionStyle: 'as',
					objectLiteralTypeAssertions: 'never'
				}
			],
			'@typescript-eslint/no-explicit-any': 'error',
			'@typescript-eslint/ban-ts-comment': [
				'error',
				{
					'ts-expect-error': true,
					'ts-ignore': true,
					'ts-nocheck': true,
					'ts-check': false
				}
			],
			// Headline type-aware rules: every unawaited promise is a race condition.
			'@typescript-eslint/no-floating-promises': 'error',
			'@typescript-eslint/no-misused-promises': 'error'
		}
	},
	{
		files: ['**/*.svelte', '**/*.svelte.ts', '**/*.svelte.js'],
		languageOptions: {
			parserOptions: {
				projectService: true,
				extraFileExtensions: ['.svelte'],
				parser: ts.parser,
				svelteConfig
			}
		}
	},
	{
		// Override or add rule settings here, such as:
		// 'svelte/button-has-type': 'error'
		rules: {
			// Typed routes are not enabled in this project (svelte.config.js has no typedRoutes: true)
			'svelte/no-navigation-without-resolve': 'off'
		}
	},
	{
		files: ['**/*.{test,spec}.{js,ts}'],
		rules: {
			// Test mocks legitimately use object-literal assertions for partial fixtures
			// (e.g. `{...} as unknown as Api`, `{ event: { url } } as ErrorArgs`), which cannot
			// be expressed as annotations. Relax the rule here instead of scattering disables.
			'@typescript-eslint/consistent-type-assertions': [
				'error',
				{ assertionStyle: 'as', objectLiteralTypeAssertions: 'allow' }
			],
			// `async` is idiomatic in vitest callbacks even without an explicit `await`
			// (the test runner itself handles the returned promise).
			'@typescript-eslint/require-await': 'off'
		}
	},
	{
		files: ['scripts/**'],
		rules: {
			// Scripts are CLI tools — console output is intentional user-facing feedback.
			'no-console': 'off'
		}
	},
	{
		files: ['tests/**/*.e2e.ts'],
		...playwright.configs['flat/recommended'],
		rules: {
			...playwright.configs['flat/recommended'].rules,
			'playwright/no-wait-for-timeout': 'error',
			'playwright/no-networkidle': 'error',
			'playwright/no-raw-locators': 'error',
			'playwright/no-element-handle': 'error',
			'playwright/no-force-option': 'error',
			'playwright/no-page-pause': 'error',
			'playwright/prefer-web-first-assertions': 'error',
			'playwright/valid-expect': 'error'
		}
	}
);
