// This file was generated by the Storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';

export type StoryblokPropertyType = 'asset' | 'multiasset' | 'multilink' | 'table' | 'richtext';
export interface StoryblokAsset {
	alt: string | null;
	copyright: string | null;
	fieldtype: 'asset';
	id: number;
	filename: string | null;
	name: string;
	title: string | null;
	focus: string | null;
	meta_data: Record<string, any>;
	source: string | null;
	is_external_url: boolean;
	is_private: boolean;
	src: string;
	updated_at: string;
	width: number | null;
	height: number | null;
	aspect_ratio: number | null;
	public_id: string | null;
	content_type: string;
}
export interface StoryblokMultiasset extends Array<StoryblokAsset> {}
export interface StoryblokMultilinkStory {
	name: string;
	created_at: string;
	published_at: string;
	id: number;
	uuid: string;
	content: Record<string, any>;
	slug: string;
	full_slug: string;
	sort_by_date?: string;
	position?: number;
	tag_list?: string[];
	is_startpage?: boolean;
	parent_id?: number | null;
	meta_data?: Record<string, any> | null;
	group_id?: string;
	first_published_at?: string;
	release_id?: number | null;
	lang?: string;
	path?: string | null;
	alternates?: any[];
	default_full_slug?: string | null;
	translated_slugs?: any[] | null;
}
export interface StoryblokMultilinkLink {
	id: number;
	uuid: string;
	slug: string;
	path: string | null;
	parent_id: number;
	name: string;
	is_folder: boolean;
	published: boolean;
	is_startpage: boolean;
	position: number;
	real_path: string;
}
export interface StoryblokMultilinkUrl {
	name: string;
	id: number;
	uuid: string;
	slug: string;
	url: string;
	full_slug: string;
}
export interface StoryblokMultilinkBase {
	fieldtype: 'multilink';
	id: string;
	url: string;
	cached_url: string;
	target?: '_blank' | '_self';
	anchor?: string;
	rel?: string;
	title?: string;
	prep?: string;
}
export type StoryblokMultilink =
	| (StoryblokMultilinkBase & {
			linktype: 'story';
			story?: StoryblokMultilinkStory | StoryblokMultilinkLink | StoryblokMultilinkUrl;
	  })
	| (StoryblokMultilinkBase & {
			linktype: 'url';
	  })
	| (StoryblokMultilinkBase & {
			linktype: 'email';
			email: string;
	  })
	| (StoryblokMultilinkBase & {
			linktype: 'asset';
	  });
export interface StoryblokTable {
	fieldtype: 'table';
	thead: Array<{
		_uid: string;
		value: string;
		component: '_table_head';
		_editable?: string;
	}>;
	tbody: Array<{
		_uid: string;
		component: '_table_row';
		_editable?: string;
		body: Array<{
			_uid: string;
			value: string;
			component: '_table_col';
			_editable?: string;
		}>;
	}>;
}
export interface StoryblokRichtext {
	type: string;
	content?: StoryblokRichtext[];
	marks?: StoryblokRichtext[];
	attrs?: Record<string, any>;
	text?: string;
}

export interface StoryblokArticleCards {
	articles?: (ISbStoryData<StoryblokBlogPost> | string)[];
	component: 'Article Cards';
	_uid: string;
}

export interface StoryblokBlogIndex {
	hero?: StoryblokHero[];
	seo?: StoryblokSEO[];
	component: 'Blog Index';
	_uid: string;
}

export interface StoryblokBlogPost {
	updated_date?: string;
	featured_image?: StoryblokAsset;
	summary?: string;
	Category?: (number | string)[];
	content?: StoryblokRichtext;
	seo?: StoryblokSEO[];
	component: 'Blog Post';
	_uid: string;
}

export interface StoryblokCalloutBlock {
	callout_type?: '' | 'info' | 'warning' | 'success';
	content?: StoryblokRichtext;
	component: 'Callout Block';
	_uid: string;
}

export interface StoryblokContactForm {
	eyebrow?: string;
	title?: string;
	fields?: StoryblokFormInput[];
	cta_text?: string;
	success_eyebrow?: string;
	success_message?: string;
	component: 'Contact Form';
	_uid: string;
}

export interface StoryblokCTA {
	label?: string;
	link?: Exclude<StoryblokMultilink, { linktype?: 'asset' }>;
	component: 'CTA';
	_uid: string;
}

export interface StoryblokFormInput {
	name?: string;
	label?: string;
	placeholder?: string;
	error_message_required?: string;
	error_message_invalid?: string;
	component: 'Form Input';
	_uid: string;
}

export interface StoryblokGlobals {
	contact_eyebrow?: string;
	contact_title?: string;
	contact_copy?: string;
	contact_cta?: StoryblokCTA[];
	seo?: StoryblokSEO[];
	contact_modal?: StoryblokContactForm[];
	component: 'Globals';
	_uid: string;
}

export interface StoryblokHero {
	title?: string;
	tagline?: string;
	copy?: string;
	CTA?: StoryblokCTA[];
	image?: StoryblokAsset;
	component: 'Hero';
	_uid: string;
}

export interface StoryblokHomePage {
	blog_eyebrow?: string;
	blog_title?: string;
	services_section_eyebrow?: string;
	services_section_title?: string;
	services_section_copy?: string;
	featured_services?: (ISbStoryData<StoryblokServicesTemplate> | string)[];
	hero_eyebrow?: string;
	hero_taglines?: (
		| ''
		| 'hardened-systems'
		| 'immersive-experiences'
		| 'captivating-stories'
		| 'sexy-interfaces'
		| 'intelligent-workflows'
	)[];
	hero_copy?: string;
	hero_cta_text?: string;
	seo?: StoryblokSEO[];
	hero_cta_url?: Exclude<StoryblokMultilink, { linktype?: 'email' } | { linktype?: 'asset' }>;
	process_eyebrow?: string;
	process_copy?: string;
	process_cards?: StoryblokProcessCards[];
	blog_copy?: string;
	articles?: StoryblokArticleCards[];
	CTA?: StoryblokCTA[];
	component: 'Home Page';
	_uid: string;
}

export interface StoryblokPage {
	body?: (
		| StoryblokArticleCards
		| StoryblokBlogIndex
		| StoryblokBlogPost
		| StoryblokCalloutBlock
		| StoryblokContactForm
		| StoryblokCTA
		| StoryblokFormInput
		| StoryblokGlobals
		| StoryblokHero
		| StoryblokHomePage
		| StoryblokPage
		| StoryblokProcessCards
		| StoryblokSEO
		| StoryblokServiceOfferCard
		| StoryblokServicesTemplate
	)[];
	component: 'page';
	_uid: string;
}

export interface StoryblokProcessCards {
	title?: string;
	copy?: string;
	component: 'Process Cards';
	_uid: string;
}

export interface StoryblokSEO {
	og_title?: string;
	og_image?: StoryblokAsset;
	meta_title?: string;
	meta_description?: string;
	no_index?: boolean;
	no_follow?: boolean;
	json_structured_data?: StoryblokRichtext;
	component: 'SEO';
	_uid: string;
}

export interface StoryblokServiceOfferCard {
	title?: string;
	copy?: string;
	pillar_id?: string;
	component: 'Service Offer Card';
	_uid: string;
}

export interface StoryblokServicesTemplate {
	hero?: StoryblokHero[];
	pillars_eyebrow?: string;
	pillars_title?: string;
	card_title?: string;
	card_list_items?: StoryblokRichtext;
	pillars_copy?: string;
	pillars?: StoryblokServiceOfferCard[];
	seo?: StoryblokSEO[];
	component: 'Services Template';
	_uid: string;
}

export type ContentType =
	| StoryblokBlogIndex
	| StoryblokBlogPost
	| StoryblokGlobals
	| StoryblokHomePage
	| StoryblokPage
	| StoryblokServicesTemplate;
