// This file was generated by the Storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from '@storyblok/js';
export type RichTextDoc = RichTextFieldValue2;
/**
 * Rich text field type - structured rich text document (ProseMirror/Tiptap format)
 */
export type RichTextFieldValue2 = {
	/**
	 * Root node type — always "doc"
	 */
	type: 'doc';
	/**
	 * Top-level rich text nodes
	 */
	content: Array<RichTextFieldValueRichTextNode>;
};
/**
 * A rich text document node
 */
export type RichTextFieldValueRichTextNode =
	| ParagraphNode
	| TextNode
	| HeadingNode
	| BlockquoteNode
	| BulletListNode
	| OrderedListNode
	| ListItemNode
	| CodeBlockNode
	| HardBreakNode
	| HorizontalRuleNode
	| ImageNode
	| EmojiNode
	| TableNode
	| TableRowNode
	| TableCellNode
	| TableHeaderNode
	| BlockNode;
/**
 * Inline formatting mark applied to a text node
 */
export type RichTextFieldValueRichTextMark =
	| LinkMark
	| BoldMark
	| ItalicMark
	| StrikeMark
	| UnderlineMark
	| CodeMark
	| SuperscriptMark
	| SubscriptMark
	| HighlightMark
	| TextStyleMark
	| AnchorMark
	| StyledMark;
export type ParagraphNode = {
	type: 'paragraph';
	attrs?: {
		/**
		 * Text alignment
		 */
		textAlign: 'left' | 'center' | 'right' | 'justify' | null;
		/**
		 * Text direction
		 */
		dir?: 'ltr' | 'rtl' | null;
	};
	content?: Array<RichTextFieldValueRichTextNode>;
	marks?: Array<RichTextFieldValueRichTextMark>;
};
export type TextNode = {
	type: 'text';
	/**
	 * The text content
	 */
	text: string;
	marks?: Array<RichTextFieldValueRichTextMark>;
};
export type HeadingNode = {
	type: 'heading';
	attrs: {
		/**
		 * Heading level (h1–h6)
		 */
		level: 1 | 2 | 3 | 4 | 5 | 6 | null;
		/**
		 * Text alignment
		 */
		textAlign: 'left' | 'center' | 'right' | 'justify' | null;
		/**
		 * Text direction
		 */
		dir?: 'ltr' | 'rtl' | null;
	};
	content?: Array<RichTextFieldValueRichTextNode>;
	marks?: Array<RichTextFieldValueRichTextMark>;
};
export type BlockquoteNode = {
	type: 'blockquote';
	attrs?: {
		/**
		 * Text direction
		 */
		dir?: 'ltr' | 'rtl' | null;
	};
	content?: Array<RichTextFieldValueRichTextNode>;
	marks?: Array<RichTextFieldValueRichTextMark>;
};
export type BulletListNode = {
	type: 'bullet_list';
	content?: Array<RichTextFieldValueRichTextNode>;
	marks?: Array<RichTextFieldValueRichTextMark>;
};
export type OrderedListNode = {
	type: 'ordered_list';
	attrs: {
		/**
		 * Starting number for the ordered list
		 */
		order?: number;
	};
	content?: Array<RichTextFieldValueRichTextNode>;
	marks?: Array<RichTextFieldValueRichTextMark>;
};
export type ListItemNode = {
	type: 'list_item';
	attrs?: {
		/**
		 * Text direction
		 */
		dir?: 'ltr' | 'rtl' | null;
	};
	content?: Array<RichTextFieldValueRichTextNode>;
	marks?: Array<RichTextFieldValueRichTextMark>;
};
export type CodeBlockNode = {
	type: 'code_block';
	attrs: {
		/**
		 * Language class (e.g. "language-typescript")
		 */
		class: string | null;
		/**
		 * Text direction
		 */
		dir?: 'ltr' | 'rtl' | null;
	};
	content?: Array<RichTextFieldValueRichTextNode>;
	marks?: Array<RichTextFieldValueRichTextMark>;
};
export type HardBreakNode = {
	type: 'hard_break';
};
export type HorizontalRuleNode = {
	type: 'horizontal_rule';
};
export type ImageNode = {
	type: 'image';
	attrs: {
		/**
		 * Storyblok asset ID
		 */
		id: number | null;
		/**
		 * Image URL
		 */
		src: string | null;
		/**
		 * Alternative text
		 */
		alt: string | null;
		title: string | null;
		source: string | null;
		copyright: string | null;
		/**
		 * Asset metadata
		 */
		meta_data: {
			alt?: string | null;
			title?: string | null;
			source?: string | null;
			copyright?: string | null;
			[key: string]: string | null | undefined;
		} | null;
	};
};
export type EmojiNode = {
	type: 'emoji';
	attrs: {
		/**
		 * Emoji name/slug
		 */
		name: string;
		/**
		 * Emoji character
		 */
		emoji: string;
		/**
		 * URL to a fallback image for unsupported environments
		 */
		fallbackImage: string;
	};
};
export type TableNode = {
	type: 'table';
	content?: Array<RichTextFieldValueRichTextNode>;
};
export type TableRowNode = {
	type: 'tableRow';
	content?: Array<RichTextFieldValueRichTextNode>;
};
export type TableCellNode = {
	type: 'tableCell';
	attrs: {
		colspan?: number;
		rowspan?: number;
		/**
		 * Column widths in pixels
		 */
		colwidth?: Array<number> | null;
		backgroundColor?: string | null;
	};
	content?: Array<RichTextFieldValueRichTextNode>;
};
export type TableHeaderNode = {
	type: 'tableHeader';
	attrs: {
		colspan?: number;
		rowspan?: number;
		/**
		 * Column widths in pixels
		 */
		colwidth?: Array<number> | null;
	};
	content?: Array<RichTextFieldValueRichTextNode>;
};
export type BlockNode = {
	type: 'blok';
	attrs: {
		/**
		 * Block instance ID
		 */
		id: string | null;
		/**
		 * Array of embedded component instances
		 */
		body: Array<BlockContentInput2> | null;
	};
};
export type LinkMark = {
	type: 'link';
	/**
	 * Link attributes
	 */
	attrs: {
		/**
		 * Link URL
		 */
		href: string | null;
		/**
		 * UUID of the linked story (for internal links)
		 */
		uuid: string | null;
		/**
		 * Anchor/fragment identifier
		 */
		anchor: string | null;
		/**
		 * Link target attribute
		 */
		target: '_self' | '_blank' | '_parent' | '_top' | null;
		/**
		 * Type of link
		 */
		linktype: 'story' | 'url' | 'email' | 'asset' | null;
		/**
		 * Custom link attributes
		 */
		custom?: {
			[key: string]: unknown;
		} | null;
	};
};
export type BoldMark = {
	type: 'bold';
};
export type ItalicMark = {
	type: 'italic';
};
export type StrikeMark = {
	type: 'strike';
};
export type UnderlineMark = {
	type: 'underline';
};
export type CodeMark = {
	type: 'code';
};
export type SuperscriptMark = {
	type: 'superscript';
};
export type SubscriptMark = {
	type: 'subscript';
};
export type HighlightMark = {
	type: 'highlight';
	attrs: {
		/**
		 * Highlight color (CSS color value)
		 */
		color: string | null;
	};
};
export type TextStyleMark = {
	type: 'textStyle';
	attrs: {
		color?: string | null;
		id?: string | null;
		class?: string | null;
	};
};
export type AnchorMark = {
	type: 'anchor';
	attrs: {
		/**
		 * Anchor identifier
		 */
		id: string;
	};
};
export type StyledMark = {
	type: 'styled';
	attrs: {
		/**
		 * CSS class name
		 */
		class: string | null;
	};
};
/**
 * Content object for creating or updating a component instance. Contains a component technical name and dynamic fields whose values depend on the component's schema field types. The _uid is optional — Storyblok will auto-generate one if not provided.
 */
export type BlockContentInput2 = {
	/**
	 * Unique identifier for this component instance (auto-generated when omitted)
	 */
	_uid?: string;
	/**
	 * Technical name of the component (content type or nestable block)
	 */
	component: string;
	/**
	 * Storyblok editor markup string for inline editing (present in draft/preview mode)
	 */
	_editable?: string;
	[key: string]:
		| null
		| string
		| number
		| boolean
		| Array<string | AssetFieldValue2 | BlockContentInput2>
		| AssetFieldValue2
		| MultilinkFieldValue2
		| TableFieldValue2
		| RichTextFieldValue2
		| PluginFieldValue2
		| undefined;
};
/**
 * Asset field type - single asset (image, video, audio, or document)
 */
export type AssetFieldValue2 = {
	/**
	 * Identifies this as an asset field
	 */
	fieldtype: 'asset';
	/**
	 * Numeric ID of the asset
	 */
	id: number | null;
	/**
	 * Alternative text for the asset
	 */
	alt: string | null;
	/**
	 * Name of the asset
	 */
	name?: string;
	/**
	 * Focal point coordinates for cropping (format "123x456:789x1011")
	 */
	focus?: string | null;
	/**
	 * Title of the asset
	 */
	title?: string | null;
	/**
	 * Source attribution for the asset
	 */
	source?: string | null;
	/**
	 * URL to the asset file
	 */
	filename: string;
	/**
	 * Copyright information
	 */
	copyright?: string | null;
	/**
	 * Additional metadata for the asset
	 */
	meta_data?: {
		[key: string]: unknown;
	};
	/**
	 * Whether the asset is hosted externally
	 */
	is_external_url?: boolean;
};
/**
 * Multilink field type - link to internal stories, external URLs, emails, or assets.
 */
export type MultilinkFieldValue2 = StoryLink | UrlLink | EmailLink | AssetLink;
/**
 * Table field type - structured table data
 */
export type TableFieldValue2 = {
	/**
	 * Table header cells
	 */
	thead: Array<{
		_uid?: string;
		component?: '_table_head';
		/**
		 * Header cell content
		 */
		value?: string;
	}>;
	/**
	 * Table body rows
	 */
	tbody: Array<{
		_uid?: string;
		component?: '_table_row';
		/**
		 * Cells in this row
		 */
		body?: Array<{
			_uid?: string;
			component?: '_table_col';
			/**
			 * Cell content
			 */
			value?: string;
		}>;
	}>;
};
/**
 * Plugin/Custom field type - field plugin with custom structure
 */
export type PluginFieldValue2 = {
	/**
	 * Technical name of the field plugin
	 */
	plugin: string;
	/**
	 * Unique identifier for this plugin field instance
	 */
	_uid?: string;
	[key: string]: unknown;
};
/**
 * Link to an internal Storyblok story.
 */
export type StoryLink = SharedLink & {
	linktype: 'story';
	/**
	 * Anchor/fragment identifier for the story link
	 */
	anchor?: string | null;
	/**
	 * Link relationship attribute
	 */
	rel?: string;
	/**
	 * Link title attribute
	 */
	title?: string;
} & {
	[key: string]: string | null;
};
/**
 * Link to an external URL.
 */
export type UrlLink = SharedLink & {
	linktype: 'url';
	/**
	 * Link relationship attribute
	 */
	rel?: string;
	/**
	 * Link title attribute
	 */
	title?: string;
} & {
	[key: string]: string;
};
/**
 * Link to an email address.
 */
export type EmailLink = SharedLink & {
	linktype: 'email';
	/**
	 * Email address
	 */
	email?: string;
};
/**
 * Link to a Storyblok asset.
 */
export type AssetLink = SharedLink & {
	linktype: 'asset';
};
export type SharedLink = {
	/**
	 * Identifies this as a multilink field
	 */
	fieldtype: 'multilink';
	/**
	 * Type of link
	 */
	linktype: string;
	/**
	 * UUID of the linked story for internal links
	 */
	id: string;
	/**
	 * URL for external links
	 */
	url: string;
	/**
	 * Cached URL path for the linked story
	 */
	cached_url: string;
	/**
	 * Link target attribute
	 */
	target?: '_self' | '_blank';
};
export type StoryblokRichTextDoc = RichTextDoc;
/** @deprecated Use StoryblokRichTextDoc instead */
export type StoryblokRichtext = StoryblokRichTextDoc;
export type StoryblokPropertyType = 'asset' | 'multiasset' | 'multilink' | 'table' | 'richtext';
export interface StoryblokAsset {
	alt: string | null;
	fieldtype: 'asset';
	id: number | null;
	filename: string | null;
	name: string;
	title: string | null;
	focus: string | null;
	copyright?: string | null;
	meta_data?: Record<string, any>;
	source?: string | null;
	is_external_url?: boolean;
	is_private?: boolean;
	src?: string;
	updated_at?: string;
	width?: number | null;
	height?: number | null;
	aspect_ratio?: number | null;
	public_id?: string | null;
	content_type?: string;
}
export interface StoryblokMultiasset extends Array<StoryblokAsset> {}
export interface StoryblokMultilinkStory {
	name: string;
	created_at: string;
	published_at: string;
	id: number;
	uuid: string;
	content: Record<string, any>;
	slug: string;
	full_slug: string;
	sort_by_date?: string;
	position?: number;
	tag_list?: string[];
	is_startpage?: boolean;
	parent_id?: number | null;
	meta_data?: Record<string, any> | null;
	group_id?: string;
	first_published_at?: string;
	release_id?: number | null;
	lang?: string;
	path?: string | null;
	alternates?: any[];
	default_full_slug?: string | null;
	translated_slugs?: any[] | null;
}
export interface StoryblokMultilinkLink {
	id: number;
	uuid: string;
	slug: string;
	path: string | null;
	parent_id: number;
	name: string;
	is_folder: boolean;
	published: boolean;
	is_startpage: boolean;
	position: number;
	real_path: string;
}
export interface StoryblokMultilinkUrl {
	name: string;
	id: number;
	uuid: string;
	slug: string;
	url: string;
	full_slug: string;
}
export interface StoryblokMultilinkBase {
	fieldtype: 'multilink';
	id: string;
	url: string;
	cached_url: string;
	target?: '_blank' | '_self';
	anchor?: string;
	rel?: string;
	title?: string;
	prep?: string;
}
export type StoryblokMultilink =
	| (StoryblokMultilinkBase & {
			linktype: 'story';
			story?: StoryblokMultilinkStory | StoryblokMultilinkLink | StoryblokMultilinkUrl;
	  })
	| (StoryblokMultilinkBase & {
			linktype: 'url';
	  })
	| (StoryblokMultilinkBase & {
			linktype: 'email';
			email: string;
	  })
	| (StoryblokMultilinkBase & {
			linktype: 'asset';
	  });
export interface StoryblokTable {
	fieldtype: 'table';
	thead: Array<{
		_uid: string;
		value: string;
		component: '_table_head';
		_editable?: string;
	}>;
	tbody: Array<{
		_uid: string;
		component: '_table_row';
		_editable?: string;
		body: Array<{
			_uid: string;
			value: string;
			component: '_table_col';
			_editable?: string;
		}>;
	}>;
}
export {
	StoryblokAsset,
	StoryblokMultiasset,
	StoryblokMultilink,
	StoryblokMultilinkLink,
	StoryblokMultilinkStory,
	StoryblokMultilinkUrl,
	StoryblokPropertyType,
	StoryblokRichTextDoc,
	StoryblokRichtext,
	StoryblokTable
};

export interface StoryblokArticleCards {
	articles?: (ISbStoryData<StoryblokBlogPost> | string)[];
	component: 'Article Cards';
	_uid: string;
	_editable?: string | undefined;
}

export interface StoryblokBlogIndex {
	hero?: StoryblokHero[];
	seo?: StoryblokSEO[];
	component: 'Blog Index';
	_uid: string;
	_editable?: string | undefined;
}

export interface StoryblokBlogPost {
	updated_date?: string;
	featured_image?: StoryblokAsset;
	summary?: string;
	Category?: (number | string)[];
	content?: StoryblokRichTextDoc;
	seo?: StoryblokSEO[];
	component: 'Blog Post';
	_uid: string;
	_editable?: string | undefined;
}

export interface StoryblokCalloutBlock {
	callout_type?: '' | 'info' | 'warning' | 'success';
	content?: StoryblokRichTextDoc;
	component: 'Callout Block';
	_uid: string;
	_editable?: string | undefined;
}

export interface StoryblokContactForm {
	eyebrow?: string;
	title?: string;
	fields?: StoryblokFormInput[];
	cta_text?: string;
	success_eyebrow?: string;
	success_message?: string;
	component: 'Contact Form';
	_uid: string;
	_editable?: string | undefined;
}

export interface StoryblokCTA {
	label?: string;
	link?: Exclude<StoryblokMultilink, { linktype?: 'asset' }>;
	component: 'CTA';
	_uid: string;
	_editable?: string | undefined;
}

export interface StoryblokFormInput {
	name?: string;
	label?: string;
	placeholder?: string;
	error_message_required?: string;
	error_message_invalid?: string;
	component: 'Form Input';
	_uid: string;
	_editable?: string | undefined;
}

export interface StoryblokGlobals {
	contact_eyebrow?: string;
	contact_title?: string;
	contact_copy?: string;
	contact_cta?: StoryblokCTA[];
	seo?: StoryblokSEO[];
	contact_modal?: StoryblokContactForm[];
	component: 'Globals';
	_uid: string;
	_editable?: string | undefined;
}

export interface StoryblokHero {
	title?: string;
	tagline?: string;
	copy?: string;
	CTA?: StoryblokCTA[];
	image?: StoryblokAsset;
	component: 'Hero';
	_uid: string;
	_editable?: string | undefined;
}

export interface StoryblokHomePage {
	blog_eyebrow?: string;
	blog_title?: string;
	services_section_eyebrow?: string;
	services_section_title?: string;
	services_section_copy?: string;
	featured_services?: (ISbStoryData<StoryblokServicesTemplate> | string)[];
	hero_eyebrow?: string;
	hero_taglines?: (
		| ''
		| 'hardened-systems'
		| 'immersive-experiences'
		| 'captivating-stories'
		| 'sexy-interfaces'
		| 'intelligent-workflows'
	)[];
	hero_copy?: string;
	hero_cta_text?: string;
	seo?: StoryblokSEO[];
	hero_cta_url?: Exclude<StoryblokMultilink, { linktype?: 'email' } | { linktype?: 'asset' }>;
	process_eyebrow?: string;
	process_copy?: string;
	process_cards?: StoryblokProcessCards[];
	blog_copy?: string;
	articles?: StoryblokArticleCards[];
	CTA?: StoryblokCTA[];
	component: 'Home Page';
	_uid: string;
	_editable?: string | undefined;
}

export interface StoryblokPage {
	body?: (
		| StoryblokArticleCards
		| StoryblokBlogIndex
		| StoryblokBlogPost
		| StoryblokCalloutBlock
		| StoryblokContactForm
		| StoryblokCTA
		| StoryblokFormInput
		| StoryblokGlobals
		| StoryblokHero
		| StoryblokHomePage
		| StoryblokPage
		| StoryblokProcessCards
		| StoryblokSEO
		| StoryblokServiceOfferCard
		| StoryblokServicesTemplate
	)[];
	component: 'page';
	_uid: string;
	_editable?: string | undefined;
}

export interface StoryblokProcessCards {
	title?: string;
	copy?: string;
	component: 'Process Cards';
	_uid: string;
	_editable?: string | undefined;
}

export interface StoryblokSEO {
	og_title?: string;
	og_image?: StoryblokAsset;
	meta_title?: string;
	meta_description?: string;
	no_index?: boolean;
	no_follow?: boolean;
	json_structured_data?: StoryblokRichTextDoc;
	component: 'SEO';
	_uid: string;
	_editable?: string | undefined;
}

export interface StoryblokServiceOfferCard {
	title?: string;
	copy?: string;
	pillar_id?: string;
	component: 'Service Offer Card';
	_uid: string;
	_editable?: string | undefined;
}

export interface StoryblokServicesTemplate {
	hero?: StoryblokHero[];
	pillars_eyebrow?: string;
	pillars_title?: string;
	card_title?: string;
	card_list_items?: StoryblokRichTextDoc;
	pillars_copy?: string;
	pillars?: StoryblokServiceOfferCard[];
	seo?: StoryblokSEO[];
	component: 'Services Template';
	_uid: string;
	_editable?: string | undefined;
}

export type ContentType =
	| StoryblokBlogIndex
	| StoryblokBlogPost
	| StoryblokGlobals
	| StoryblokHomePage
	| StoryblokPage
	| StoryblokServicesTemplate;
